name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python $
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.3
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r assignment2/requirements.txt
    - name: Run Migrations
      run: python manage.py migrate
      working-directory: ./assignment2/
    - name: Run Tests
      run: |
        python manage.py test
      working-directory: ./assignment2/
